apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_NAME: "HEMIS Univer Backend"
  APP_URL: "https://api.univer.uz"
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

  DB_CONNECTION: "pgsql"
  DB_PORT: "5432"

  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"

  REDIS_PORT: "6379"

  JWT_TTL: "60"
  JWT_REFRESH_TTL: "20160"

  CORS_ALLOWED_ORIGINS: "https://univer.uz,https://app.univer.uz"
