apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: univer-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.univer.uz
    secretName: univer-backend-tls
  rules:
  - host: api.univer.uz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: univer-backend-service
            port:
              number: 80
